version: "3.9"

services:
  db:
    image: postgres:16
    container_name: schoolme_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: schoolme
    ports:
      - "10000:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d schoolme || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: schoolme_redis
    # ✅ No cambies el puerto interno; usa el default 6379
    command: >
      sh -lc '
        exec redis-server
          --bind 0.0.0.0
          --appendonly yes
      '
    ports:
      # Host:Contenedor  => abre 4001 solo hacia tu máquina
      - "${REDIS_PORT:-4001}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 6379 ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./Web/Dockerfile
    container_name: schoolme_api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT:-Production}"
      ASPNETCORE_URLS: "http://+:7000"
      DB_ENGINE: ${DB_ENGINE:-Postgres}
      # DB_ENGINE:"Postgres

      # PostgreSQL (interna)
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=schoolme;Username=postgres;Password=${POSTGRES_PASSWORD:-postgres}"
      ConnectionStrings__PgAdmin: "Host=db;Port=5432;Database=schoolme;Username=postgres;Password=${POSTGRES_PASSWORD:-postgres}"

      # ✅ Redis (interna): SIEMPRE redis:6379 entre contenedores
      ConnectionStrings__Redis: "redis:6379,abortConnect=false,connectRetry=5,connectTimeout=15000,syncTimeout=15000,keepAlive=60"

      # Azure Storage
      AZURE_STORAGE_CONNECTION: ${AZURE_STORAGE_CONNECTION}

      # CORS
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS} 
    ports:
      - "7000:7000"
    restart: unless-stopped

volumes:
  pg_data:
  redis_data:

